import {
  Box,
  BoxArt,
  BoxHero,
  BoxHeros,
  BoxStroke,
  BoxValorant,
  ContainerBody,
  Valorant,
} from "./styled";

export function BodyComponent() {
  return (
    <ContainerBody>
      <BoxValorant>
        <Valorant
          className="Valorant"
          src="/../public/Valorant.svg"
          alt="valorant"
          width="468"
          height="73"
        />
        <BoxHeros>
          <BoxHero>
            <BoxStroke>
              <Valorant
                className="Stroke"
                src="/../public/stroke.png"
                width="170"
                height="170"
              />
            </BoxStroke>
            <Box>
              <Valorant
                className="omem"
                src="/../public/Omem.png"
                alt="omem"
                width="170"
                height="170"
              />
            </Box>
          </BoxHero>
          <BoxHero>
            <BoxStroke>
              <Valorant
                className="Stroke"
                src="/../public/stroke.png"
                width="170"
                height="170"
              />
            </BoxStroke>
            <Box>
              <Valorant
                className="Sage"
                src="/../public/Sage.png"
                alt="Sage"
                width="170"
                height="170"
              />
            </Box>
          </BoxHero>
          <BoxHero>
            <BoxStroke>
              <Valorant
                className="Stroke"
                src="/../public/stroke.png"
                width="170"
                height="170"
              />
            </BoxStroke>
            <Box>
              <Valorant
                className="Sova"
                src="/../public/Sova.png"
                alt="Sova"
                width="170"
                height="170"
              />
            </Box>
          </BoxHero>
        </BoxHeros>
      </BoxValorant>
      <BoxArt>
        <Valorant
          className="art"
          src="/../public/Art.png"
          alt="art"
          width="398"
          height="492"
        />
      </BoxArt>
    </ContainerBody>
  );
}
